name: Precision Fitness
favicon: null
layout_spectrum: 0.4500885063316673
typography_spectrum: 0.22338105062954128
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5464667323976755
  lightness: 0.7895718179643154
  saturation: 0.026045181788504124
  rhythmicContrast: 0.5650734272785485
purpose: []
